class MigrateData < ActiveRecord::Migration
  def self.up
    Badge.create :name => "一应俱全", :metal => "铜"
    Badge.create :name => "兴致盎然", :metal => "银"
    Badge.create :name => "躬耕不辍", :metal => "金"
    Badge.create :name => "初窥门径", :metal => "铜"
    Badge.create :name => "初出茅庐", :metal => "铜"
    Badge.create :name => "略知一二", :metal => "铜"
    Badge.create :name => "非比寻常", :metal => "银"
    Badge.create :name => "所向披靡", :metal => "金"
    Badge.create :name => "出类拔萃", :metal => "铜"
    Badge.create :name => "罕有敌手", :metal => "银"
    Badge.create :name => "一代宗师", :metal => "金"
    Badge.create :name => "牛刀小试", :metal => "铜"
    Badge.create :name => "登堂入室", :metal => "银"
    Badge.create :name => "精深奥妙", :metal => "金"
    Badge.create :name => "秦砖汉瓦", :metal => "银"
    Badge.create :name => "和壁隋珠", :metal => "金"
    Question.create :user_id => 1, :tag_list => "GSM,开源,加密算法,破解", :title => "谷歌未能按期履行洛杉矶市软件提供合约", :body => "谷歌在赢得向洛杉矶市政府提供邮件与协作软件的高额订单后，错过了6月30日这一软件全面运行最终期限，因对该公司软件安全的关注加剧。"
    Question.create :user_id => 1, :tag_list => "GSM,开源,加密算法,破解", :title => "开源GSM加密算法破解软件发布", :body => "谷歌在赢得向洛杉矶市政府提供邮件与协作软件的高额订单后，错过了6月30日这一软件全面运行最终期限，因对该公司软件安全的关注加剧。"
    Question.create :user_id => 1, :tag_list => "GSM,开源,加密算法,破解", :title => "开源GSM加密算法破解软件发布", :body => "谷歌在赢得向洛杉矶市政府提供邮件与协作软件的高额订单后，错过了6月30日这一软件全面运行最终期限，因对该公司软件安全的关注加剧。"
    Question.create :user_id => 1, :tag_list => "GSM,开源,加密算法,破解", :title => "开源GSM加密算法破解软件发布", :body => "谷歌在赢得向洛杉矶市政府提供邮件与协作软件的高额订单后，错过了6月30日这一软件全面运行最终期限，因对该公司软件安全的关注加剧。"
    Question.create :user_id => 1, :tag_list => "GSM,开源,加密算法,破解", :title => "开源GSM加密算法破解软件发布", :body => "谷歌在赢得向洛杉矶市政府提供邮件与协作软件的高额订单后，错过了6月30日这一软件全面运行最终期限，因对该公司软件安全的关注加剧。"
    Question.create :user_id => 1, :tag_list => "GSM,开源,加密算法,破解", :title => "开源GSM加密算法破解软件发布", :body => "谷歌在赢得向洛杉矶市政府提供邮件与协作软件的高额订单后，错过了6月30日这一软件全面运行最终期限，因对该公司软件安全的关注加剧。"
    Question.create :user_id => 1, :tag_list => "GSM,开源,加密算法,破解", :title => "开源GSM加密算法破解软件发布", :body => "谷歌在赢得向洛杉矶市政府提供邮件与协作软件的高额订单后，错过了6月30日这一软件全面运行最终期限，因对该公司软件安全的关注加剧。"
    Question.create :user_id => 1, :tag_list => "GSM,开源,加密算法,破解", :title => "开源GSM加密算法破解软件发布", :body => "谷歌在赢得向洛杉矶市政府提供邮件与协作软件的高额订单后，错过了6月30日这一软件全面运行最终期限，因对该公司软件安全的关注加剧。"
    Question.create :user_id => 1, :tag_list => "GSM,开源,加密算法,破解", :title => "开源GSM加密算法破解软件发布", :body => "谷歌在赢得向洛杉矶市政府提供邮件与协作软件的高额订单后，错过了6月30日这一软件全面运行最终期限，因对该公司软件安全的关注加剧。"
    Question.create :user_id => 1, :tag_list => "GSM,开源,加密算法,破解", :title => "开源GSM加密算法破解软件发布", :body => "谷歌在赢得向洛杉矶市政府提供邮件与协作软件的高额订单后，错过了6月30日这一软件全面运行最终期限，因对该公司软件安全的关注加剧。"
    Question.create :user_id => 1, :tag_list => "GSM,开源,加密算法,破解", :title => "开源GSM加密算法破解软件发布", :body => "谷歌在赢得向洛杉矶市政府提供邮件与协作软件的高额订单后，错过了6月30日这一软件全面运行最终期限，因对该公司软件安全的关注加剧。"
    Question.create :user_id => 1, :tag_list => "GSM,开源,加密算法,破解", :title => "开源GSM加密算法破解软件发布", :body => "谷歌在赢得向洛杉矶市政府提供邮件与协作软件的高额订单后，错过了6月30日这一软件全面运行最终期限，因对该公司软件安全的关注加剧。"
    Question.create :user_id => 1, :tag_list => "GSM,开源,加密算法,破解", :title => "开源GSM加密算法破解软件发布", :body => "谷歌在赢得向洛杉矶市政府提供邮件与协作软件的高额订单后，错过了6月30日这一软件全面运行最终期限，因对该公司软件安全的关注加剧。"
    Question.create :user_id => 1, :tag_list => "GSM,开源,加密算法,破解", :title => "开源GSM加密算法破解软件发布", :body => "谷歌在赢得向洛杉矶市政府提供邮件与协作软件的高额订单后，错过了6月30日这一软件全面运行最终期限，因对该公司软件安全的关注加剧。"
    Question.create :user_id => 1, :tag_list => "GSM,开源,加密算法,破解", :title => "开源GSM加密算法破解软件发布", :body => "谷歌在赢得向洛杉矶市政府提供邮件与协作软件的高额订单后，错过了6月30日这一软件全面运行最终期限，因对该公司软件安全的关注加剧。"
    Question.create :user_id => 1, :tag_list => "GSM,开源,加密算法,破解", :title => "开源GSM加密算法破解软件发布", :body => "谷歌在赢得向洛杉矶市政府提供邮件与协作软件的高额订单后，错过了6月30日这一软件全面运行最终期限，因对该公司软件安全的关注加剧。"
    Question.create :user_id => 1, :tag_list => "GSM,开源,加密算法,破解", :title => "开源GSM加密算法破解软件发布", :body => "谷歌在赢得向洛杉矶市政府提供邮件与协作软件的高额订单后，错过了6月30日这一软件全面运行最终期限，因对该公司软件安全的关注加剧。"
    Question.create :user_id => 1, :tag_list => "GSM,开源,加密算法,破解", :title => "开源GSM加密算法破解软件发布", :body => "谷歌在赢得向洛杉矶市政府提供邮件与协作软件的高额订单后，错过了6月30日这一软件全面运行最终期限，因对该公司软件安全的关注加剧。"
    Question.create :user_id => 1, :tag_list => "GSM,开源,加密算法,破解", :title => "开源GSM加密算法破解软件发布", :body => "谷歌在赢得向洛杉矶市政府提供邮件与协作软件的高额订单后，错过了6月30日这一软件全面运行最终期限，因对该公司软件安全的关注加剧。"
    Question.create :user_id => 1, :tag_list => "GSM,开源,加密算法,破解", :title => "开源GSM加密算法破解软件发布", :body => "谷歌在赢得向洛杉矶市政府提供邮件与协作软件的高额订单后，错过了6月30日这一软件全面运行最终期限，因对该公司软件安全的关注加剧。"
    Question.create :user_id => 1, :tag_list => "GSM,开源,加密算法,破解", :title => "开源GSM加密算法破解软件发布", :body => "谷歌在赢得向洛杉矶市政府提供邮件与协作软件的高额订单后，错过了6月30日这一软件全面运行最终期限，因对该公司软件安全的关注加剧。"
    Question.create :user_id => 1, :tag_list => "GSM,开源,加密算法,破解", :title => "开源GSM加密算法破解软件发布", :body => "谷歌在赢得向洛杉矶市政府提供邮件与协作软件的高额订单后，错过了6月30日这一软件全面运行最终期限，因对该公司软件安全的关注加剧。"
    Question.create :user_id => 1, :tag_list => "GSM,开源,加密算法,破解", :title => "开源GSM加密算法破解软件发布", :body => "谷歌在赢得向洛杉矶市政府提供邮件与协作软件的高额订单后，错过了6月30日这一软件全面运行最终期限，因对该公司软件安全的关注加剧。"
    Question.create :user_id => 1, :tag_list => "GSM,开源,加密算法,破解", :title => "开源GSM加密算法破解软件发布", :body => "谷歌在赢得向洛杉矶市政府提供邮件与协作软件的高额订单后，错过了6月30日这一软件全面运行最终期限，因对该公司软件安全的关注加剧。"
    Question.create :user_id => 1, :tag_list => "GSM,开源,加密算法,破解", :title => "开源GSM加密算法破解软件发布", :body => "谷歌在赢得向洛杉矶市政府提供邮件与协作软件的高额订单后，错过了6月30日这一软件全面运行最终期限，因对该公司软件安全的关注加剧。"
    Question.create :user_id => 1, :tag_list => "GSM,开源,加密算法,破解", :title => "开源GSM加密算法破解软件发布", :body => "谷歌在赢得向洛杉矶市政府提供邮件与协作软件的高额订单后，错过了6月30日这一软件全面运行最终期限，因对该公司软件安全的关注加剧。"
    Question.create :user_id => 1, :tag_list => "GSM,开源,加密算法,破解", :title => "开源GSM加密算法破解软件发布", :body => "谷歌在赢得向洛杉矶市政府提供邮件与协作软件的高额订单后，错过了6月30日这一软件全面运行最终期限，因对该公司软件安全的关注加剧。"
    Question.create :user_id => 1, :tag_list => "GSM,开源,加密算法,破解", :title => "开源GSM加密算法破解软件发布", :body => "谷歌在赢得向洛杉矶市政府提供邮件与协作软件的高额订单后，错过了6月30日这一软件全面运行最终期限，因对该公司软件安全的关注加剧。"
    Question.create :user_id => 1, :tag_list => "GSM,开源,加密算法,破解", :title => "开源GSM加密算法破解软件发布", :body => "谷歌在赢得向洛杉矶市政府提供邮件与协作软件的高额订单后，错过了6月30日这一软件全面运行最终期限，因对该公司软件安全的关注加剧。"
    Question.create :user_id => 1, :tag_list => "GSM,开源,加密算法,破解", :title => "开源GSM加密算法破解软件发布", :body => "谷歌在赢得向洛杉矶市政府提供邮件与协作软件的高额订单后，错过了6月30日这一软件全面运行最终期限，因对该公司软件安全的关注加剧。"
    Question.create :user_id => 1, :tag_list => "GSM,开源,加密算法,破解", :title => "开源GSM加密算法破解软件发布", :body => "谷歌在赢得向洛杉矶市政府提供邮件与协作软件的高额订单后，错过了6月30日这一软件全面运行最终期限，因对该公司软件安全的关注加剧。"
  end

  def self.down
  end
end
